class VerificationError(Exception):
    pass

class UserNotFoundError(Exception):
    pass